version: '3'
services: 
    hello-vue:
        build: .
        ports: 
            - 8080:8080
        container_name: vue-app

networks:
    defualt:
        external: 
            name: intregrated-int221
